baseURL = "https://friedokra.dev/" # Your domain name. Must end with "/"
title = "Howdy Y'all"
languageCode = "en-us" # Default language for multilingual sites
theme = "hello-friend-ng"

PygmentsCodeFences = true
PygmentsStyle = "monokai"

paginate = 15
rssLimit = 15
copyright = ""

archetypeDir = "archetypes"
contentDir   = "content"
layoutDir    = "layouts"
publishDir   = "public"

buildDrafts = false
buildFuture = false
buildExpired = false
canonifyURLs = false

enableRobotsTXT = true
enableGitInfo   = false
enableEmoji     = true
enableMissingTranslationPlaceholders = false
disableRSS     = false
disableSitemap = false
disable404     = false
disableHugoGeneratorInject = false

[author]
  name = "Stephen Houston"

[blackfriday]
  hrefTargetBlank = true

[taxonomies]
  tag      = "tags"
  category = "categories"
  series   = "series"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  description = "Ramblings and Hobbies of a Software Engineer"
  keywords = ""
  images = ["/images/okra_bg.jpg"]

  homeSubtitle = "Software Engineer"

  gitUrl = ""

  enableThemeToggle = true
  enableSharingButtons = true

  customCSS = []
  customJS  = []

  justifyContent = false

  [params.footer]
    trademark = true
    rss = true
    copyright = false
    author = true
    topText = []
    bottomText = [
      "Powered by <a href=\"http://gohugo.io\">Hugo</a>",
      "Made with &#10084; by <a href=\"https://github.com/rhazdon\">Djordje Atlialp</a>"
    ]

  [params.logo]
    logoText = "howdy y'all"
    logoHomeLink = "/"
    logoCursorColor = "#669966"

  [[params.social]]
    name = "github"
    url = "https://github.com/okratitan"

  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/stephenmhouston"

  [[params.social]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/stephenmhouston"

  [[params.social]]
    name = "email"
    url = "mailto:smhouston88@gmail.com"

[languages]
  [languages.en]
    title = "Stephen Houston"
    subtitle = "Software Engineer"
    copyright = ""

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "about/"

  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "posts/"

  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "projects/"

  [[menu.main]]
    identifier = "resume"
    name = "Resume"
    url = "resume/"
