baseURL = "https://okra.technology/" # Your domain name. Must end with "/"
theme = "hello-friend-ng"
languageCode = "en-us" # Default language for multilingual sites
paginate = 5
buildDrafts = false
buildFuture = false
buildExpired = false
canonifyURLs = true
enableRobotsTXT = true
enableGitInfo = false
enableEmoji = true
disableRSS = false
disableSitemap = false
disable404 = false
disableHugoGeneratorInject = false
archetypeDir = "archetypes"
contentDir   = "content"
layoutDir    = "layouts"
publishDir   = "public"

[author]
name = "Stephen Houston"

[params]
contentTypeName = "blog"
defaultTheme = "dark"
showReadingTime = false
enableThemeToggle = true
homeSubtitle = "Software Engineer"
enableSharingButtons = true
gitUrl = ""

[params.logo]
logoText = "howdy y'all"
logoHomeLink = "/"
logoCursorColor = "#669966"

[params.footer]
trademark = true
rss = true
copyright = false
author = true
topText = []
bottomText = [
  "Powered by <a href=\"http://gohugo.io\">Hugo</a>",
  "Made with &#10084; by <a href=\"https://github.com/rhazdon\">Djordje Atlialp</a>"
]

[languages.en]
title = "Stephen Houston"
subtitle = "Software Engineer"
keywords = ""
copyright = ""
menuMore = "Show more"
writtenBy = "Written by"
readMore = "Read more"
readOtherPosts = "Read other posts"
newerPosts = "Newer posts"
olderPosts = "Older posts"
minuteReadingTime = "min read"
dateFormatSingle = "2006-01-02"
dateFormatList = "2006-01-02"

[[menu.main]]
identifier = "about"
name = "About"
url = "about/"

[[menu.main]]
identifier = "blog"
name = "Blog"
url = "posts/"

[[menu.main]]
identifier = "projects"
name = "Projects"
url = "projects/"

[[menu.main]]
identifier = "resume"
name = "Resume"
url = "resume/"

# Social icons
[[params.social]]
name = "github"
url = "https://github.com/okratitan"

[[params.social]]
name = "twitter"
url = "https://twitter.com/stephenmhouston"

[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/stephenmhouston"

[[params.social]]
name = "email"
url = "mailto:smhouston88@gmail.com"
